# Docker image base
image: ros:kinetic-ros-base

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - mkdir ~/catkin_ws
          - ln -s $BITBUCKET_CLONE_DIR ~/catkin_ws/src
          - cd ~/catkin_ws
          - apt-get update
          - apt-get install sudo -y  # Needed by rosdep
          - rosdep update
          - rosdep install --from-paths src --ignore-src
          - catkin_make
          - catkin_make roslint
          - catkin_make run_tests