# Docker image base
image: ros:kinetic-ros-base

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - mkdir ~/catkin_ws
          - ln -s $BITBUCKET_CLONE_DIR ~/catkin_ws/src
          - cd ~/catkin_ws
          - apt-get update
          - apt-get install sudo clang-format-3.8 -y  # Needed by rosdep
          - rosdep update
          - rosdep install -y --from-paths src --ignore-src
          - source /opt/ros/*/setup.bash
          - cd  $BITBUCKET_CLONE_DIR
          - git ls-files | grep -E '\.[ch](pp)?$' |  xargs clang-format-3.8 --style=file -i && git diff --exit-code || { git reset --hard; false; }
          - cd ~/catkin_ws
          - catkin_make
          - catkin_make run_tests && catkin_test_results